In [ ]:
!apt-get update -qq

!pip install -q pyspark pandas matplotlib

W: Skipping acquire of configured file 'main/source/Sources' as repository 'https://r2u.stat.illinois.edu/ubuntu jammy InRelease' does not seem to provide it (sources.list entry misspelt?)

In [ ]:
import pandas as pd
import random

from datetime import datetime, timedelta

In [ ]:

random.seed(10)

nombres = ["Carlos", "Manuel", "Saul", "Lucía", "María", "Pedro", "Ana", "Jorge", "Sofía", "Luis"]
apellidos = ["Ramirez", "Fernandes", "Sosa", "García", "Torres", "Lopez", "Martinez", "Rojas", "Castillo", "Vega"]

# Generar 200 DNIs únicos
dnis_unicos = random.sample(range(10000000, 99999999), 200)

data = []
for i in range(1, 201):
    nombre = random.choice(nombres)
    apellido = random.choice(apellidos)
    dni = str(dnis_unicos[i-1])  # siempre único
    telefono = "9" + str(random.randint(10000000, 99999999))
    direccion = "Calle " + str(random.randint(1, 200)) + " #" + str(random.randint(100, 999))

    data.append([i, nombre, apellido, dni, telefono, direccion])

df = pd.DataFrame(data, columns=["IdCliente","Nombre","Apellido","DNI","Telefono","Direccion"])

print(df.head())

   IdCliente Nombre   Apellido       DNI   Telefono       Direccion
0          1  Pedro       Vega  86692358  963777009   Calle 50 #458
1          2   Saul  Fernandes  14373493  989386257   Calle 50 #536
2          3  Lucía  Fernandes  67564514  951406688  Calle 119 #983
3          4  Sofía   Martinez  74768331  970078848  Calle 171 #861
4          5  Sofía     García  87590101  945687128  Calle 153 #473

In [ ]:
df.to_csv("ClienteServicioTecnico.csv",index=False)

In [ ]:
df_pandas = pd.read_csv("ClienteServicioTecnico.csv")

In [ ]:
df_pandas.head()

   IdCliente Nombre  Apellido       DNI   Telefono       Direccion
0          1   Luis   Ramirez  67564514  974768331  Calle 148 #115
1          2  Lucía     Rojas  75940689  947248192  Calle 168 #930
2          3   Saul   Ramirez  79883058  975778173   Calle 84 #177
3          4  Lucía     Lopez  15980256  966424622   Calle 36 #717
4          5  Pedro  Martinez  66541096  948066592  Calle 173 #368

In [ ]:
roles = ["Administrador", "Tecnico", "Cliente"]

data = []
for i, rol in enumerate(roles, start=1):
    data.append([i, rol])

df = pd.DataFrame(data, columns=["IdRol","NombreRol"])
print(df.head())

   IdRol      NombreRol
0      1  Administrador
1      2        Tecnico
2      3        Cliente

In [ ]:
df.to_csv("RolServicioTecnico.csv", index=False)

In [ ]:
df1_pandas = pd.read_csv("RolServicioTecnico.csv")

In [ ]:
df1_pandas.head()

   IdRol      NombreRol
0      1  Administrador
1      2        Tecnico
2      3        Cliente

In [ ]:
random.seed(10)

nombres_usuario = ["admin01", "tecnico01", "cliente01", "tecnico02", "cliente02"]
roles = [1, 2, 3, 2, 3]

data = []
for i in range(len(nombres_usuario)):
    usuario = nombres_usuario[i]
    clave = "pass" + str(random.randint(1000,9999))
    idrol = roles[i]
    estado = 1  # activo por defecto


    data.append([usuario, clave, idrol, estado])


df = pd.DataFrame(data, columns=["Usuario","Clave","IdRol","Estado"])

In [ ]:
df.to_csv("UsuarioServicioTecnico.csv", index=False)

In [ ]:
df2_pandas = pd.read_csv("UsuarioServicioTecnico.csv")

In [ ]:
df2_pandas.head()

   IdUsuario NombreUsuario                 Correo Contraseña  IdRol
0          1       admin01    admin01@empresa.com   pass1533      1
1          2     tecnico01  tecnico01@empresa.com   pass8026      2
2          3     cliente01    cliente01@gmail.com   pass8906      3
3          4     tecnico02  tecnico02@empresa.com   pass1243      2
4          5     cliente02    cliente02@gmail.com   pass4376      3

In [ ]:

random.seed(10)

nombres = ["Juan", "Pedro", "Lucía", "María", "Carlos", "Ana", "José", "Sofía"]
apellidos = ["Ramirez", "Fernandes", "Sosa", "García", "Torres", "Lopez", "Martinez", "Rojas"]
especialidades = ["Hardware", "Software", "Redes", "Electrónica", "Mantenimiento"]

data = []

for i in range(1, 51):
    nombre = random.choice(nombres)
    apellido = random.choice(apellidos)
    especialidad = random.choice(especialidades)
    telefono = "9" + str(random.randint(10000000, 99999999))

    data.append([nombre, apellido, especialidad, telefono])

df = pd.DataFrame(data, columns=["Nombre", "Apellido", "Especialidad", "Telefono"])
print(df.head())

   Nombre  Apellido Especialidad   Telefono
0    Juan  Martinez  Electrónica  987590101
1    Juan    García  Electrónica  975940689
2  Carlos      Sosa     Hardware  979883058
3   Sofía     Lopez     Hardware  943553985
4     Ana   Ramirez  Electrónica  928614559

In [ ]:
print(df.shape)

(50, 5)

In [ ]:
df.to_csv("TecnicoServicioTecnico.csv", index=False)

In [ ]:
df3_pandas = pd.read_csv("TecnicoServicioTecnico.csv")

In [ ]:
df3_pandas.head()

   IdTecnico         Nombre Especialidad   Telefono                     Correo
0          1  Juan Martinez  Electrónica  987590101  juan.martinez@empresa.com
1          2    Juan García  Electrónica  975940689    juan.garcía@empresa.com
2          3    Carlos Sosa     Hardware  979883058    carlos.sosa@empresa.com
3          4    Sofía Lopez     Hardware  943553985    sofía.lopez@empresa.com
4          5    Ana Ramirez  Electrónica  928614559    ana.ramirez@empresa.com

In [ ]:
random.seed(20)


tipos = ["Laptop", "PC", "Celular", "Tablet", "Impresora"]
marcas = ["Dell", "HP", "Lenovo", "Samsung", "Apple", "Canon"]

data = []

num_clientes = 200

for i in range(1,101):
    tipo = random.choice(tipos)
    marca = random.choice(marcas)
    modelo = tipo[:3].upper() + str(random.randint(100,999))
    serie = "SN" + str(random.randint(10000,99999))
    id_cliente = random.randint(1,num_clientes)  # FK hacia Cliente

    data.append([
        i,
        tipo,
        marca,
        modelo,
        serie,
        id_cliente
    ])

df = pd.DataFrame(data, columns=["IdEquipo","Tipo","Marca","Modelo","Serie","IdCliente"])
print(df.head())

   IdEquipo     Tipo   Marca  Modelo    Serie  IdCliente
0         1       PC  Lenovo   PC790  SN93325         26
1         2  Celular   Apple  CEL273  SN13536        106
2         3   Tablet    Dell  TAB205  SN26394         82
3         4   Tablet   Apple  TAB560  SN63999         54
4         5       PC  Lenovo   PC740  SN99301         86

In [ ]:
df.to_csv("EquipoServicioTecnico.csv", index=False)

In [ ]:
df4_pandas = pd.read_csv("EquipoServicioTecnico.csv")

In [ ]:
df4_pandas.head()

   IdEquipo     Tipo   Marca  Modelo    Serie  IdCliente
0         1       PC  Lenovo   PC790  SN93325         26
1         2  Celular   Apple  CEL273  SN13536        106
2         3   Tablet    Dell  TAB205  SN26394         82
3         4   Tablet   Apple  TAB560  SN63999         54
4         5       PC  Lenovo   PC740  SN99301         86

In [ ]:
servicios = [
    ("Mantenimiento preventivo", 50.00),
    ("Reparación de hardware", 120.00),
    ("Instalación de software", 80.00),
    ("Diagnóstico general", 40.00),
    ("Reparación de pantalla", 150.00),
    ("Cambio de batería", 100.00),
    ("Configuración de red", 90.00),
    ("Limpieza interna", 60.00)
]

data = []

for i, (nombre, costo) in enumerate(servicios, start=1):
    data.append([i, nombre, costo])

df = pd.DataFrame(data, columns=["IdServicio","NombreServicio","Costo"])

print(df)

   IdServicio            NombreServicio  Costo
0           1  Mantenimiento preventivo   50.0
1           2    Reparación de hardware  120.0
2           3   Instalación de software   80.0
3           4       Diagnóstico general   40.0
4           5    Reparación de pantalla  150.0
5           6         Cambio de batería  100.0
6           7      Configuración de red   90.0
7           8          Limpieza interna   60.0

In [ ]:
df.to_csv("ServicioServicioTecnico.csv", index=False)

In [ ]:
df5_pandas = pd.read_csv("ServicioServicioTecnico.csv")

In [ ]:
df5_pandas.head()

   IdServicio            NombreServicio  Costo
0           1  Mantenimiento preventivo   50.0
1           2    Reparación de hardware  120.0
2           3   Instalación de software   80.0
3           4       Diagnóstico general   40.0
4           5    Reparación de pantalla  150.0

In [ ]:
repuestos = [
    ("Pantalla LCD", 200.00),
    ("Batería de laptop", 120.00),
    ("Memoria RAM 8GB", 80.00),
    ("Disco SSD 256GB", 150.00),
    ("Fuente de poder", 100.00),
    ("Teclado", 60.00),
    ("Mouse", 25.00),
    ("Placa madre", 250.00),
    ("Cargador universal", 40.00),
    ("Cable HDMI", 15.00)
]

data = []
for i, (nombre, costo) in enumerate(repuestos, start=1):
    data.append([i, nombre, costo])
df = pd.DataFrame(data, columns=["IdRepuesto","NombreRepuesto","Costo"])

print(df)

   IdRepuesto      NombreRepuesto  Costo
0           1        Pantalla LCD  200.0
1           2   Batería de laptop  120.0
2           3     Memoria RAM 8GB   80.0
3           4     Disco SSD 256GB  150.0
4           5     Fuente de poder  100.0
5           6             Teclado   60.0
6           7               Mouse   25.0
7           8         Placa madre  250.0
8           9  Cargador universal   40.0
9          10          Cable HDMI   15.0

In [ ]:
df.to_csv("RepuestosServicioTecnico.csv", index=False)

In [ ]:
random.seed(30)

num_clientes = 200
num_tecnicos = 50
num_equipos = 100

estados = ["Pendiente", "En proceso", "Finalizado", "Cancelado"]
observaciones = [
    "Revisión inicial del equipo",
    "Cambio de pieza principal",
    "Actualización de software",
    "Limpieza y mantenimiento",
    "Diagnóstico completo",
    "Cliente solicita revisión adicional",
    "Equipo entregado sin fallas",
    "Pendiente de repuesto"
]

data = []
for i in range(1, 101):
    id_cliente = random.randint(1, num_clientes)
    id_tecnico = random.randint(1, num_tecnicos)
    id_equipo = random.randint(1, num_equipos)
    fecha = datetime(2026, 7, 1) + timedelta(days=random.randint(0, 30))
    estado = random.choice(estados)
    observacion = random.choice(observaciones)

    data.append([
        id_cliente,
        id_tecnico,
        id_equipo,
        fecha.strftime("%Y-%m-%d"),
        estado,
        observacion
    ])

# Crear DataFrame (sin IdOrden porque es IDENTITY)
df = pd.DataFrame(data, columns=["IdCliente","IdTecnico","IdEquipo","FechaIngreso","Estado","Observacion"])
print(df.head())

   IdCliente  IdTecnico  IdEquipo FechaIngreso      Estado  \
0        139         19        79   2026-07-01  En proceso
1         13         26        49   2026-07-21  En proceso
2        119          1        67   2026-07-30  En proceso
3         19         11        77   2026-07-17   Cancelado
4        138          5        52   2026-07-01  En proceso

                           Observacion
0                 Diagnóstico completo
1            Cambio de pieza principal
2          Revisión inicial del equipo
3  Cliente solicita revisión adicional
4                 Diagnóstico completo

In [ ]:
df.to_csv("OrdenServicioServicioTecnico.csv", index=False)

In [ ]:
random.seed(40)
num_ordenes = 100   # número de órdenes cargadas en tu tabla
num_servicios = 8   # catálogo de servicios
num_detalles = 200  # cantidad de filas de detalle que quieres generar

data = []

for i in range(1, num_detalles+1):
    id_orden = random.randint(1, num_ordenes)   # siempre entre 1 y 100
    id_servicio = random.randint(1, num_servicios)
    cantidad = random.randint(1, 3)
    subtotal = cantidad * random.randint(40, 150)

    data.append([i, id_orden, id_servicio, cantidad, subtotal])

df = pd.DataFrame(data, columns=["IdDetalleOrden","IdOrden","IdServicio","Cantidad","Subtotal"])
print(df.head())

   IdDetalleOrden  IdOrden  IdServicio  Cantidad  Subtotal
0               1       59           1         1        76
1               2       86           4         1       137
2               3       45           5         3       288
3               4        4           3         1       122
4               5       26           8         1        62

In [ ]:
df.to_csv("DetalleOrdenServicioTecnico.csv", index=False)

In [ ]:
random.seed(50)


num_ordenes = 150
num_repuestos = 10

data = []

for i in range(1,201):
    id_orden = random.randint(1,num_ordenes)
    id_repuesto = random.randint(1,num_repuestos)
    cantidad = random.randint(1,5)  # cantidad de piezas usadas
    subtotal = cantidad * random.randint(15,250)  # costo simulado

    data.append([
        i,
        id_orden,
        id_repuesto,
        cantidad,
        subtotal
    ])

df = pd.DataFrame(data, columns=["IdDetalleRepuesto","IdOrden","IdRepuesto","Cantidad","Subtotal"])

print(df.head())

   IdDetalleRepuesto  IdOrden  IdRepuesto  Cantidad  Subtotal
0                  1      128           5         3       534
1                  2       63           8         3       108
2                  3      138           6         2       376
3                  4      143           2         2       206
4                  5       26           6         3       213

In [ ]:
df.to_csv("DetalleRepuestoServicioTecnico.csv", index=False)

In [ ]:
random.seed(40)
num_ordenes = 100
num_repuestos = 10
num_detalles = 200

data = []

for i in range(1, num_detalles+1):
    id_detalle = i
    id_orden = random.randint(1, num_ordenes)   # siempre entre 1 y 100
    id_repuesto = random.randint(1, num_repuestos)  # siempre entre 1 y 10
    cantidad = random.randint(1, 5)
    subtotal = cantidad * random.randint(20, 100)

    data.append([id_detalle, id_orden, id_repuesto, cantidad, subtotal])

df = pd.DataFrame(data, columns=["IdDetalleRepuesto","IdOrden","IdRepuesto","Cantidad","Subtotal"])
print(df.head())

   IdDetalleRepuesto  IdOrden  IdRepuesto  Cantidad  Subtotal
0                  1       59          10         5       120
1                  2       32           5         2        72
2                  3       98           6         3       228
3                  4        4           9         2        54
4                  5       83           4         5       390

In [ ]:
df.to_csv("DetalleRepuestoServicioTecnico.csv", index=False)

In [ ]:
import pandas as pd
import random

# Cargar tu archivo original
df = pd.read_csv("ClienteServicioTecnico.csv")

# Detectar DNIs repetidos
conteo = df["DNI"].value_counts()
repetidos = conteo[conteo > 1].index

# Generar nuevos DNIs únicos para reemplazar los repetidos
usados = set(df["DNI"])
for idx in df[df["DNI"].isin(repetidos)].index:
    while True:
        nuevo_dni = str(random.randint(10000000, 99999999))
        if nuevo_dni not in usados:
            df.at[idx, "DNI"] = nuevo_dni
            usados.add(nuevo_dni)
            break

# Reasignar IdCliente consecutivo
df["IdCliente"] = range(1, len(df) + 1)

In [ ]:
print(df.head())

   IdCliente Nombre   Apellido       DNI   Telefono       Direccion
0          1  Pedro       Vega  86692358  963777009   Calle 50 #458
1          2   Saul  Fernandes  14373493  989386257   Calle 50 #536
2          3  Lucía  Fernandes  67564514  951406688  Calle 119 #983
3          4  Sofía   Martinez  74768331  970078848  Calle 171 #861
4          5  Sofía     García  87590101  945687128  Calle 153 #473

In [ ]:
df.to_csv("ClienteServicioTecnico.csv", index=False)

In [ ]:
import pandas as pd
import random

# Cargar tu archivo
df = pd.read_csv("ClienteServicioTecnico.csv")

# Guardar los DNIs ya usados
usados = set(df["DNI"])

# Detectar filas con DNIs repetidos
duplicados = df[df.duplicated(subset="DNI", keep=False)]

# Reemplazar los DNIs repetidos con nuevos únicos
for idx in duplicados.index:
    while True:
        nuevo_dni = str(random.randint(10000000, 99999999))
        if nuevo_dni not in usados:
            df.at[idx, "DNI"] = nuevo_dni
            usados.add(nuevo_dni)
            break

# Reasignar IdCliente consecutivo
df["IdCliente"] = range(1, len(df) + 1)

# Guardar archivo corregido
df.to_csv("ClienteCorregido.csv", index=False)

In [ ]:
df = pd.read_csv("ClienteFinal.csv")

# Crear un conjunto con los DNIs ya usados
usados = set()

# Recorrer todas las filas y corregir si hay repetidos
for idx in df.index:
    dni = str(df.at[idx, "DNI"])
    if dni in usados:
        # Generar un nuevo DNI único
        while True:
            nuevo_dni = str(random.randint(10000000, 99999999))
            if nuevo_dni not in usados:
                df.at[idx, "DNI"] = nuevo_dni
                usados.add(nuevo_dni)
                break
    else:
        usados.add(dni)

# Reasignar IdCliente consecutivo
df["IdCliente"] = range(1, len(df) + 1)

# Guardar archivo limpio
df.to_csv("ClienteUnico.csv", index=False)

In [ ]:
df = pd.read_csv("ClienteUnico.csv")

# Verificar si hay DNIs repetidos
repetidos = df[df.duplicated(subset="DNI", keep=False)]

if repetidos.empty:
    print("✅ No hay DNIs repetidos. El archivo está limpio.")
else:
    print("⚠️ Se encontraron DNIs repetidos:")
    print(repetidos[["IdCliente","Nombre","Apellido","DNI"]])

✅ No hay DNIs repetidos. El archivo está limpio.